version: "3"

services:
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:6.0-alpine3.14
    volumes:
      - .:/src
    working_dir: /src
    command: tail -f /dev/null
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000