version: "3"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091